spring:
  application:
    name: persistance_with_spring_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/udemy4?useTimezone=true&serverTimezone=UTC
    username: root
    password: Art.DB25
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: true
logging:
  level:
    root: Warn
    com.arthur_pereira.First.REST.Endpoint: Warn